# Generated by Django 2.2.9 on 2020-03-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=20)),
                ('squad', models.CharField(max_length=100)),
                ('matches_played', models.IntegerField(default=0)),
                ('starts', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('ast', models.IntegerField(default=0)),
                ('np_goals', models.IntegerField(default=0)),
                ('gls_and_ast', models.IntegerField(default=0)),
            ],
        ),
    ]
