# Generated by Django 2.2.9 on 2020-03-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
